### ISSUE TITLE
文中式(3)(4)有误,故无法根据得出HS-ResNet参数更少的结论

### ISSUE THREAD

**Issue by henbucuoshanghai** [bobo0810/HS-ResNet#1]
那算完后   参数多了多少？

有一个东西 3*3模块的输入  和输出  channel 一样吗？？
不一样的话   后面1*1 维度对不上了。。。

怎么回事

**Comment by bobo0810** [comment]
> 那算完后 参数多了多少？
> 
> 有一个东西 3_3模块的输入 和输出 channel 一样吗？？ 不一样的话 后面1_1 维度对不上了。。。
> 
> 怎么回事

1. 计算量增大。对比仓库的公式与 论文公式（3）。原文缺平方
2.论文表格对比看出，参数量也是增大的。

**Comment by henbucuoshanghai** [comment]
那维度变化的话   后面1*1  维度怎么变呢？

**Comment by bobo0810** [comment]
> 那维度变化的话 后面1*1 维度怎么变呢？

3×3替换为HS-Block之后，输入输出的尺度和通道均未变，仅仅block内部计算更复杂了。建议详细看下 HS-Block内部框架图，很形象。

**Comment by henbucuoshanghai** [comment]
输入输出的尺度和通道均未变    不会吧、、、

**Comment by bobo0810** [comment]
> 输入输出的尺度和通道均未变 不会吧、、、

@henbucuoshanghai 从框架图看，手动数一下图中不同特征的通道数，结论 : 输入输出的通道尺度均未变。
![792054d646d10c617e3c6721fbd876e](https://user-images.githubusercontent.com/26057879/102035258-e94a2180-3dfa-11eb-9dbe-e213323fcfd1.png)
