### ISSUE TITLE
超参数S的选择

### ISSUE THREAD

**Issue by 81961916** [bobo0810/HS-ResNet#2]
你好，请问为什么将分组数s改为文章中的5会报错呢

**Comment by bobo0810** [comment]
> 你好，请问为什么将分组数s改为文章中的5会报错呢

@81961916 你好，报错原因为无法整除导致通道数计算不一致问题。当前统一init和forward方法的通道数计算，支持[分组数S](https://github.com/bobo0810/HS-ResNet/blob/0eba0157ddc919425a9ee9699e3c17ca6be58419/hsresnet/hs_block.py#L7)自由设置。现已更新，感谢关注。:smiley:

**Comment by 81961916** [comment]
好的，谢谢
