### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by kevinkkkkkkkk** [bobo0810/HS-ResNet#4]
请问一下，这个有pytorch版的预训练模型嘛，还是可以直接使用resnet的预训练模型呢

**Comment by bobo0810** [comment]
> 请问一下，这个有pytorch版的预训练模型嘛，还是可以直接使用resnet的预训练模型呢

很抱歉，由于没有足够训练资源，所以无法提供预训练权重。

**Comment by kevinkkkkkkkk** [comment]
> > 请问一下，这个有pytorch版的预训练模型嘛，还是可以直接使用resnet的预训练模型呢
> 
> 很抱歉，由于没有足够训练资源，所以无法提供预训练权重。

好的感谢，那我从头训练一下，请问一下一般其余的参数都是怎么设置的呢，比如学习率那些

**Comment by bobo0810** [comment]
> 好的感谢，那我从头训练一下，请问一下一般其余的参数都是怎么设置的呢，比如学习率那些

你好，训练ImageNet的github库很多，可以直接替换backbone训练。具体参数可参考原论文~
如果可以，期待提供权重，我将不胜感激。😊
